//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string accountNumber { get; set; }
        public string accountType { get; set; }
        public Nullable<double> sanctionedLimit { get; set; }
        public Nullable<double> undisbursed { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> arrears { get; set; }
        public Nullable<double> roi { get; set; }
        public string period { get; set; }
        public Nullable<double> cashMargin { get; set; }
        public Nullable<System.DateTime> lastUpdateOn { get; set; }
        public string lastUpdateBy { get; set; }
    }
}
