//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustDocument
    {
        public int Id { get; set; }
        public string Cust_id { get; set; }
        public string Periodicity { get; set; }
        public string DocumentType { get; set; }
        public string Submitted { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string DeviationNoted { get; set; }
        public Nullable<System.DateTime> CompiledDate { get; set; }
        public Nullable<int> IsChecked { get; set; }
        public string MonitorId { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdatedOn { get; set; }
    }
}
