//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Comments { get; set; }
        public string RelatedTo { get; set; }
        public string Module { get; set; }
        public string URL { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> UploadOn { get; set; }
    }
}
