//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialResultDetail
    {
        public long ID { get; set; }
        public Nullable<int> HeaderID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ResQuarter { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Cust_id { get; set; }
        public string Trends { get; set; }
    
        public virtual FinancialResultHeader FinancialResultHeader { get; set; }
    }
}
