//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamutdatabaseEntities : DbContext
    {
        public gamutdatabaseEntities()
            : base("name=gamutdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<General> Generals { get; set; }
        public virtual DbSet<LookUp> LookUps { get; set; }
        public virtual DbSet<SOC124> SOC124 { get; set; }
        public virtual DbSet<GeneralExposure> GeneralExposures { get; set; }
        public virtual DbSet<GeneralGurantor> GeneralGurantors { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<FinancialResultDetail> FinancialResultDetails { get; set; }
        public virtual DbSet<FinancialResultHeader> FinancialResultHeaders { get; set; }
        public virtual DbSet<FinancialResultType> FinancialResultTypes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RestucturingDetail> RestucturingDetails { get; set; }
        public virtual DbSet<RestucturingHeader> RestucturingHeaders { get; set; }
        public virtual DbSet<WarningIndicator> WarningIndicators { get; set; }
        public virtual DbSet<AccountDetail> AccountDetails { get; set; }
        public virtual DbSet<CustomerDataMapping> CustomerDataMappings { get; set; }
        public virtual DbSet<CustDocument> CustDocuments { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<SMABucket> SMABuckets { get; set; }
        public virtual DbSet<SMACompilation> SMACompilations { get; set; }
        public virtual DbSet<SMAHistory> SMAHistories { get; set; }
        public virtual DbSet<Snapshot> Snapshots { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
    }
}
