//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        public string Cust_id { get; set; }
        public string Activity { get; set; }
        public string Sector_SubSector { get; set; }
        public string Priority_Non_Priority { get; set; }
        public string Govt_sponsored { get; set; }
        public string Industry { get; set; }
        public string Incorporation { get; set; }
        public string Connection_Since { get; set; }
        public string Internal_Rating { get; set; }
        public string External_Rating { get; set; }
        public string Banking_Argmt { get; set; }
        public string If_Consortium { get; set; }
        public string Lead_Bank { get; set; }
        public string SMA { get; set; }
        public string DCCO { get; set; }
        public string Takeover { get; set; }
        public string Takeover_From { get; set; }
        public string Reason_for_Takeover { get; set; }
        public Nullable<double> Working_capital_L { get; set; }
        public Nullable<double> Term_Load_L { get; set; }
        public Nullable<double> Bank_Gurantee_L { get; set; }
        public Nullable<double> Letter_of_credit_L { get; set; }
        public Nullable<double> PCL_L { get; set; }
        public Nullable<double> Bill_Purchase_L { get; set; }
        public Nullable<double> Working_capital_B { get; set; }
        public Nullable<double> Term_Load_B { get; set; }
        public Nullable<double> Bank_Gurantee_B { get; set; }
        public Nullable<double> Letter_of_credit_B { get; set; }
        public Nullable<double> PCL_B { get; set; }
        public Nullable<double> Bill_Purchase_B { get; set; }
        public Nullable<double> Working_capital_E { get; set; }
        public Nullable<double> Term_Load_E { get; set; }
        public Nullable<double> Bank_Gurantee_E { get; set; }
        public Nullable<double> Letter_of_credit_E { get; set; }
        public Nullable<double> PCL_E { get; set; }
        public Nullable<double> Bill_Purchase_E { get; set; }
        public string Defaults { get; set; }
        public Nullable<System.DateTime> Defaults_As_On { get; set; }
        public string Gurantor_1 { get; set; }
        public string Gurantor_2 { get; set; }
        public string Promoter_1 { get; set; }
        public string Promoter_2 { get; set; }
        public string Promoter_3 { get; set; }
        public Nullable<System.DateTime> Internal_Rating_AsOn { get; set; }
        public Nullable<System.DateTime> External_Rating_AsOn { get; set; }
        public Nullable<System.DateTime> DCCO_AsOn { get; set; }
        public Nullable<System.DateTime> Takeover_AsOn { get; set; }
        public string Inspection_Comments { get; set; }
    }
}
