//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralGurantor
    {
        public int id { get; set; }
        public string Cust_Id { get; set; }
        public string gurCust_Id { get; set; }
        public string gurType { get; set; }
    }
}
