//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string AuditType { get; set; }
        public string Code { get; set; }
        public string Comments { get; set; }
        public string InspectionStatus { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<System.DateTime> CompiledDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
