//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string accountNo { get; set; }
        public string accountType { get; set; }
        public string roi { get; set; }
        public Nullable<double> asperID { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string schemeType { get; set; }
        public Nullable<System.DateTime> followUpDate { get; set; }
        public Nullable<System.DateTime> compiledDate { get; set; }
        public string source { get; set; }
    }
}
