//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscExposure
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string FacilityType { get; set; }
        public string Facility { get; set; }
        public Nullable<double> SanctionLimit { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Exposure { get; set; }
        public string Comments { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
