//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleNote
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string ModuleName { get; set; }
        public string ObservationNotes { get; set; }
        public string CommunicatedTo { get; set; }
        public string responceReceived { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
