//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long NewsID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Source { get; set; }
        public string Heading { get; set; }
        public string Url { get; set; }
        public string Cust_id { get; set; }
        public string Comments { get; set; }
        public string InformedTo { get; set; }
    }
}
