//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestucturingDetail
    {
        public int Id { get; set; }
        public string Cust_id { get; set; }
        public string accountNo { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> accountDate { get; set; }
        public Nullable<System.DateTime> cutofDate { get; set; }
        public Nullable<double> sacrifice { get; set; }
        public Nullable<System.DateTime> repaymentStartDate { get; set; }
        public string frequency { get; set; }
    }
}
