//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestucturingHeader
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string accountRestructured { get; set; }
        public string accountRescheduled { get; set; }
        public string idNo { get; set; }
        public Nullable<System.DateTime> soApplicationDate { get; set; }
        public string checkedByCRMD { get; set; }
        public string pfNo { get; set; }
        public Nullable<System.DateTime> followupDate { get; set; }
        public Nullable<System.DateTime> accountRegularisedDate { get; set; }
        public string projectType { get; set; }
        public Nullable<System.DateTime> dccoDate { get; set; }
        public Nullable<System.DateTime> ExtendedDate { get; set; }
        public Nullable<System.DateTime> actualDate { get; set; }
    }
}
