//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMABucket
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string bucket { get; set; }
        public string banksFICounts { get; set; }
        public string numberFIBanks { get; set; }
        public string unregularisedDays { get; set; }
        public string noOfFI { get; set; }
        public string regularised { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
        public Nullable<System.DateTime> lastupdatedOn { get; set; }
        public string lastupdatedBy { get; set; }
    }
}
