//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMACompilation
    {
        public int Id { get; set; }
        public string Cust_id { get; set; }
        public string JLF { get; set; }
        public Nullable<System.DateTime> smaDate { get; set; }
        public string calledBy { get; set; }
        public string meeetingSummary { get; set; }
        public string branchReply { get; set; }
        public Nullable<System.DateTime> nextFollowupDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
