//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMAHistory
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string smaClass { get; set; }
        public string accountNumber { get; set; }
        public string reason { get; set; }
        public Nullable<int> noOfDays { get; set; }
        public string nextStatus { get; set; }
        public Nullable<System.DateTime> smaDate { get; set; }
        public Nullable<System.DateTime> CompiledDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string LastUpdateBy { get; set; }
    }
}
