//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snapshot
    {
        public int Id { get; set; }
        public string Cust_Id { get; set; }
        public string snapshotType { get; set; }
        public string data1Description { get; set; }
        public string data1Value { get; set; }
        public string data2Description { get; set; }
        public string data2Value { get; set; }
        public string data3Description { get; set; }
        public string data3Value { get; set; }
        public string data4Description { get; set; }
        public string data4Value { get; set; }
        public string data5Description { get; set; }
        public string data5Value { get; set; }
        public Nullable<System.DateTime> lastUpdatedOn { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<System.DateTime> compiledDate { get; set; }
        public string snapshotDescription { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
