//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOC124
    {
        public int Id { get; set; }
        public string Cust_id { get; set; }
        public string sourceSystemId { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string via { get; set; }
        public string approvalFor { get; set; }
        public string isCompiled { get; set; }
        public Nullable<System.DateTime> followUpDate { get; set; }
        public Nullable<System.DateTime> compiledDate { get; set; }
        public string DocumnetURL { get; set; }
    }
}
