//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamut.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Cust_id { get; set; }
        public string Cust_Name { get; set; }
        public string Pan_No { get; set; }
        public Nullable<double> Exposure { get; set; }
        public Nullable<System.DateTime> Exposure_AsOn { get; set; }
        public string Constitution { get; set; }
    }
}
